<a href="https://colab.research.google.com/github/4060e031/AI_and_security_2020/blob/master/20201007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/tensorflow/examples --depth 1

Cloning into 'examples'...
remote: Enumerating objects: 1861, done.
remote: Counting objects: 100% (1861/1861), done.
remote: Compressing objects: 100% (1170/1170), done.
remote: Total 1861 (delta 529), reused 1467 (delta 405), pack-reused 0
Receiving objects: 100% (1861/1861), 12.24 MiB | 15.03 MiB/s, done.
Resolving deltas: 100% (529/529), done.


In [ ]:
ls

examples/  sample_data/


In [ ]:
ls /examples/*.*

ls: cannot access '/examples/*.*': No such file or directory


In [ ]:
cp /example

cp: missing destination file operand after '/example'
Try 'cp --help' for more information.


In [1]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]])
# ar2.shape
ar2.ndim

2

In [2]:
ar=np.array([2,4,6,8]); 
ar.dtype

dtype('int64')

In [3]:
f_ar = np.array([13,-3,8.88])
f_ar

intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [7]:
import numpy as np
ar9 = np.eye(3);
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
import numpy as np
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
import numpy as np
np.ones((4, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [10]:
import numpy as np
np.arange(2, 3, 0.1) # start, end, step

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [11]:
import numpy as np
np.linspace(1., 4., 6) # start, end, num

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [12]:
import numpy as np
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [13]:
import numpy as np
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [14]:
import numpy as np
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [15]:
import numpy as np
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [16]:
import numpy as np
ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [17]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [18]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [19]:
import numpy as np
a = np.array([0, 1, 2])
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])